### PR TITLE
Add containerbuild and push to ghcr.io

### PR DESCRIPTION
**Pull request by bengtfredh**
## Description

Add containerbuild and push to ghcr.io

## Related Issue(s)
- #{issue number}
N/A

## Verification
- [x] **Your** code builds clean without any errors or warnings
- [x] Manual testing done (required)
- [N/A] Relevant automated test added (if you find this hard, leave it and we'll help out)
- [N/A] All tests run green

## Documentation
- [N/A] User documentation is updated with a separate linked PR in [altinn-studio-docs.](https://github.com/Altinn/altinn-studio-docs) (if applicable)

### CODE REVIEW

**Comment by tjololo** [comment]
Permissions can be granted on a job basis: https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs

**Comment by alt-how** [comment]
@altinnadmin Can you fix the permissions?

**Comment by altinnadmin** [comment]
@bengtfredh @alt-how The default permissions of this repo is "Read and write permissions".

**Comment by bengtfredh** [comment]
@tjololo @altinnadmin @alt-how 
FYI: Permissions was not working on the forked branch in PR. When merged to master it works. Looks like you need more permissions if you want to run actions on fork. We probably do not want to enable this setting.

image

**Comment by tjololo** [comment]
Agreed, giving write permissions to forks seems like at accident waiting to happen.

**Pull request merged**
